CONFIG = {"seed": 42,
          "epochs": 3,
          "model_name": "microsoft/deberta-v3-base",
          "train_batch_size": 8,
          "valid_batch_size": 16,
          "max_length": 512,
          "learning_rate": 2e-5,
          "scheduler": 'CosineAnnealingLR',
          # "new_scheduler":cosine,
          # "min_lr": 1e-6,
          # "T_max": 500,
          # "weight_decay": 0.01,
          # "n_fold": 5,
          # "n_accumulate": 1,
          # "num_classes": 3,
          # "device": torch.device("cuda:0" if torch.cuda.is_available() else "cpu"),
          # "hash_name": HASH_NAME,
          "competition": "FeedBack",
          "_wandb_kernel": "deb",
          "fc_dropout":0.2,
          "gradient_checkpoint" : True,
          "decay":0.01,
          "eps":1e-6,
          "betas":(0.9, 0.999),
          "warmup_steps":0.2,
          "num_cycles":0.5,
          }

print(CONFIG.seed)